vim.g.mapleader = " "
-- vim.keymap.set("n", "<leader>e", vim.cmd.Ex)
vim.keymap.set({ "n", "v" }, "<leader>y", [["+y]])
vim.keymap.set("n", "<leader>Y", [["+Y]])
vim.keymap.set("i", "<C-c>", "<Esc>")
vim.keymap.set("n", "<leader>s", [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>]])
vim.keymap.set("n", "<leader>tp", ":tabp<CR>")
vim.keymap.set("n", "<leader>tn", ":tabn<CR>")
vim.keymap.set("n", "<leader>tt", ":tabnew<CR>")
vim.keymap.set("n", "<leader>tc", ":tabclose<CR>")
vim.keymap.set("n", "<leader>j", ":m+1<CR>")
vim.keymap.set("n", "<leader>k", ":m-1<CR>")
vim.keymap.set("i", "<C-j>", [[<C-\><C-n>:call search('[>)\]}"'']', 'W')<CR>a]])
vim.keymap.set('n', '<leader>f', vim.lsp.buf.format)
vim.keymap.set('v', '<leader>p', '"_dP')
vim.keymap.set("n", "<C-j>", "<C-w><C-j>")
vim.keymap.set("n", "<C-k>", "<C-w><C-k>")
vim.keymap.set("n", "<C-h>", "<C-w><C-h>")
vim.keymap.set("n", "<C-l>", "<C-w><C-l>")
vim.keymap.set("n", "<M-,>", "<C-w>5<")
vim.keymap.set("n", "<M-.>", "<C-w>5>")
vim.keymap.set("n", "<M-[>", "<C-w>5+")
vim.keymap.set("n", "<M-]>", "<C-w>5-")
vim.keymap.set('n', '<leader>td', function()
  vim.diagnostic.enable(not vim.diagnostic.is_enabled())
end, { silent = true, noremap = true })
vim.keymap.set('n', '<leader>hi', function()
  local result = vim.treesitter.get_captures_at_cursor(0)
  print(vim.inspect(result))
end, { noremap = true, silent = false })
vim.keymap.set("n", "<leader>th", ":botright 16split | terminal<CR>")
vim.keymap.set("t", "<c-j>", "<c-\\><c-n><c-w><c-j>")
vim.keymap.set("t", "<c-k>", "<c-\\><c-n><c-w><c-k>")
vim.keymap.set("t", "<c-h>", "<c-\\><c-n><c-w><c-h>")
vim.keymap.set("t", "<c-l>", "<c-\\><c-n><c-w><c-l>")
vim.keymap.set("t", "<M-,>", "<c-\\><c-n><C-w>5<")
vim.keymap.set("t", "<M-.>", "<c-\\><c-n><C-w>5>")
vim.keymap.set("t", "<M-[>", "<c-\\><c-n><C-w>5+")
vim.keymap.set("t", "<M-]>", "<c-\\><c-n><C-w>5-")
vim.keymap.set("t", "<Esc>", "<C-\\><C-n>")
